/**
 * Extract the audio that was embedded in the original single-file build.
 *
 *   node scripts/extract-assets.mjs [--source <path-to-RobotWarrior.html>]
 *
 * The original carried every track and voice line as a base64 string literal inside
 * two ~12 MB lines of JavaScript. This writes them back out as real files and
 * regenerates `src/data/audio-manifest.js`, which is the list the game loads from.
 *
 * Two destinations, deliberately different:
 *
 *   assets/audio/voice/  40 short mission voice lines. Generated for this game and
 *                        committed with it.
 *   assets/audio/music/  3 tracks from the MechWarrior 2 soundtrack. Commercial
 *                        recordings, so they are gitignored and never published.
 *                        The game plays fine without them. See docs/assets.md.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const argv = process.argv.slice(2);
const sourceArg = argv.indexOf('--source');
const SOURCE = path.resolve(ROOT, sourceArg >= 0 ? argv[sourceArg + 1] : 'RobotWarrior.html');

if (!fs.existsSync(SOURCE)) {
  console.error(
    `Source build not found: ${path.relative(ROOT, SOURCE)}\n\n` +
      'The original single-file build is not part of this repository (it embeds the\n' +
      'copyrighted soundtrack). Point the extractor at your own copy:\n\n' +
      '  node scripts/extract-assets.mjs --source path/to/RobotWarrior.html\n',
  );
  process.exit(1);
}

const lines = fs.readFileSync(SOURCE, 'utf8').split('\n');

/** Pull one `const NAME={...}` line and parse its JSON object literal. */
function readBlob(name) {
  const line = lines.find((l) => l.startsWith(`const ${name}={`));
  if (!line) throw new Error(`${name} not found in ${path.basename(SOURCE)}`);
  const json = line.slice(line.indexOf('={') + 1).replace(/;?\s*$/, '');
  return JSON.parse(json);
}

/** Identify the container from its magic bytes rather than trusting a name. */
function extensionOf(buf) {
  if (buf.subarray(0, 4).toString('latin1') === 'OggS') return 'ogg';
  if (buf.subarray(0, 3).toString('latin1') === 'ID3') return 'mp3';
  if (buf[0] === 0xff && (buf[1] & 0xe0) === 0xe0) return 'mp3';
  throw new Error('unrecognised audio container: ' + buf.subarray(0, 4).toString('hex'));
}

function emit(blobName, dir) {
  const out = path.join(ROOT, dir);
  fs.mkdirSync(out, { recursive: true });
  const written = [];
  for (const [key, b64] of Object.entries(readBlob(blobName))) {
    const buf = Buffer.from(b64, 'base64');
    const ext = extensionOf(buf);
    fs.writeFileSync(path.join(out, `${key}.${ext}`), buf);
    written.push({ key, ext, bytes: buf.length });
  }
  const total = written.reduce((n, w) => n + w.bytes, 0);
  console.log(
    `${dir.padEnd(22)} ${String(written.length).padStart(3)} files  ${(total / 1048576).toFixed(2)} MB`,
  );
  return written;
}

const music = emit('SOUNDTRACK_DATA', 'assets/audio/music');
const voice = emit('VOICE_DATA', 'assets/audio/voice');

// --- regenerate the manifest the game loads from ----------------------------
const manifest = `/**
 * Audio manifest — GENERATED by scripts/extract-assets.mjs. Do not edit by hand.
 *
 * The original build inlined every clip as base64. Audio now loads over the network
 * from the files that script writes, so this list is the single place that knows
 * which clips exist and what container each one uses.
 *
 * Music is an optional local asset and is not distributed with the source; a missing
 * track degrades to silence. See docs/assets.md.
 */

// Vite rewrites BASE_URL at build time, so the same source works when the game is
// served from "/" in development and from "/robot-warrior/" on GitHub Pages.
const BASE = import.meta.env?.BASE_URL ?? '/';

/** @typedef {{ key: string, ext: 'mp3' | 'ogg' }} Clip */

/** Mission soundtrack cue keys, in load order. @type {Clip[]} */
export const MUSIC_CLIPS = ${JSON.stringify(
  music.map(({ key, ext }) => ({ key, ext })),
  null,
  2,
)
  .replace(/\n/g, '\n')
  .replace(/"([a-zA-Z]+)":/g, '$1:')
  .replace(/"/g, "'")};

/** Radio and cockpit voice lines. @type {Clip[]} */
export const VOICE_CLIPS = ${JSON.stringify(
  voice.map(({ key, ext }) => ({ key, ext })),
  null,
  2,
)
  .replace(/"([a-zA-Z]+)":/g, '$1:')
  .replace(/"/g, "'")};

const MUSIC_EXT = Object.fromEntries(MUSIC_CLIPS.map((c) => [c.key, c.ext]));

/**
 * URL for a soundtrack cue.
 * @param {string} key
 */
export function musicUrl(key) {
  return \`\${BASE}audio/music/\${key}.\${MUSIC_EXT[key] ?? 'mp3'}\`;
}

/**
 * URL for a voice clip.
 * @param {Clip} clip
 */
export function voiceUrl(clip) {
  return \`\${BASE}audio/voice/\${clip.key}.\${clip.ext}\`;
}
`;

const manifestPath = path.join(ROOT, 'src/data/audio-manifest.js');
fs.mkdirSync(path.dirname(manifestPath), { recursive: true });
fs.writeFileSync(manifestPath, manifest);
console.log('src/data/audio-manifest.js  regenerated');
